[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
major_version = 17

[auth]
enabled = true

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8083

[analytics]
enabled = true
port = 54327
