import { db } from '@/lib/db/dexie-db';
import type { Product, Program, SubscriptionPlan, Sale, Employee, Absence, PayrollRecord } from '@/lib/db/dexie-db';

export interface SyncEntityConfig<T> {
  dexieTable: any;
  supabaseTable: string;
  rpcName: string;
  toCloudRecord: (item: Partial<T> & { id?: number }) => Record<string, any>;
  fromCloudRecord: (record: any) => T;
}

export const ENTITY_REGISTRY: Record<string, SyncEntityConfig<any>> = {
  products: {
    dexieTable: db.products as any,
    supabaseTable: 'synced_products',
    rpcName: 'upsert_synced_product',
    toCloudRecord: (item: Partial<Product> & { id?: number }) => ({
      p_local_id: item.id,
      p_barcode: item.barcode || '',
      p_name: item.name || '',
      p_buy_price: item.buyPrice ?? 0,
      p_sell_price: item.sellPrice ?? 0,
      p_stock: item.stock ?? 0,
      p_photo: item.photo || '',
    }),
    fromCloudRecord: (r: any): Product => ({
      id: r.local_id,
      barcode: r.barcode || '',
      name: r.name || '',
      buyPrice: Number(r.buy_price) || 0,
      sellPrice: Number(r.sell_price) || 0,
      stock: r.stock || 0,
      photo: r.photo || '',
      createdAt: new Date(r.created_at || Date.now()),
    }),
  },

  programs: {
    dexieTable: db.programs as any,
    supabaseTable: 'synced_programs',
    rpcName: 'upsert_synced_program',
    toCloudRecord: (item: Partial<Program> & { id?: number }) => ({
      p_local_id: item.id,
      p_name: item.name || '',
      p_description: item.description || '',
      p_price: item.price ?? 0,
      p_is_active: item.isActive ?? true,
    }),
    fromCloudRecord: (r: any): Program => ({
      id: r.local_id,
      name: r.name || '',
      description: r.description || '',
      price: Number(r.price) || 0,
      isActive: r.is_active ?? true,
      createdAt: new Date(r.created_at || Date.now()),
    }),
  },

  sales: {
    dexieTable: db.sales as any,
    supabaseTable: 'synced_sales',
    rpcName: 'upsert_synced_sale',
    toCloudRecord: (item: Partial<Sale> & { id?: number }) => ({
      p_local_id: item.id,
      p_items_json: JSON.stringify(item.items || []),
      p_total: item.total ?? 0,
      p_paid: item.paid ?? 0,
      p_change_amount: item.change ?? 0,
      p_payment_mode: item.paymentMode || 'cash',
    }),
    fromCloudRecord: (r: any): Sale => ({
      id: r.local_id,
      items: JSON.parse(r.items_json || '[]'),
      total: Number(r.total) || 0,
      paid: Number(r.paid) || 0,
      change: Number(r.change_amount) || 0,
      paymentMode: r.payment_mode || 'cash',
      createdAt: new Date(r.created_at || Date.now()),
      updatedAt: new Date(r.updated_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  employees: {
    dexieTable: db.employees as any,
    supabaseTable: 'synced_employees',
    rpcName: 'upsert_synced_employee',
    toCloudRecord: (item: Partial<Employee> & { id?: number }) => ({
      p_local_id: item.id,
      p_gym_user_id: item.gymUserId || null,
      p_coach_id: item.coachId || null,
      p_name: item.name || '',
      p_phone: item.phone || '',
      p_email: item.email || '',
      p_address: item.address || '',
      p_position: item.position || '',
      p_department: item.department || '',
      p_hire_date: item.hireDate || '',
      p_contract_type: item.contractType || 'cdi',
      p_base_salary: item.baseSalary ?? 0,
      p_bank_name: item.bankName || '',
      p_bank_rib: item.bankRib || '',
      p_emergency_contact: item.emergencyContact || '',
      p_emergency_phone: item.emergencyPhone || '',
      p_social_security: item.socialSecurityNumber || '',
      p_birth_date: item.birthDate || '',
      p_gender: item.gender || 'other',
      p_photo: item.photo || '',
      p_is_active: item.isActive ?? true,
    }),
    fromCloudRecord: (r: any): Employee => ({
      id: r.local_id,
      gymUserId: r.gym_user_id || undefined,
      coachId: r.coach_id || undefined,
      name: r.name || '',
      phone: r.phone || '',
      email: r.email || '',
      address: r.address || '',
      position: r.position || '',
      department: r.department || '',
      hireDate: r.hire_date || '',
      contractType: r.contract_type || 'cdi',
      baseSalary: Number(r.base_salary) || 0,
      bankName: r.bank_name || '',
      bankRib: r.bank_rib || '',
      emergencyContact: r.emergency_contact || '',
      emergencyPhone: r.emergency_phone || '',
      socialSecurityNumber: r.social_security || '',
      birthDate: r.birth_date || '',
      gender: r.gender || 'other',
      photo: r.photo || '',
      isActive: r.is_active ?? true,
      createdAt: new Date(r.created_at || Date.now()),
      updatedAt: new Date(r.updated_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  absences: {
    dexieTable: db.absences as any,
    supabaseTable: 'synced_absences',
    rpcName: 'upsert_synced_absence',
    toCloudRecord: (item: Partial<Absence> & { id?: number }) => ({
      p_local_id: item.id,
      p_employee_id: item.employeeId ?? 0,
      p_type: item.type || 'other',
      p_start_date: item.startDate || '',
      p_end_date: item.endDate || '',
      p_reason: item.reason || '',
      p_status: item.status || 'pending',
      p_approved_by: item.approvedBy || null,
    }),
    fromCloudRecord: (r: any): Absence => ({
      id: r.local_id,
      employeeId: r.employee_id ?? 0,
      type: r.type || 'other',
      startDate: r.start_date || '',
      endDate: r.end_date || '',
      reason: r.reason || '',
      status: r.status || 'pending',
      approvedBy: r.approved_by || undefined,
      createdAt: new Date(r.created_at || Date.now()),
      updatedAt: new Date(r.updated_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  payrollRecords: {
    dexieTable: db.payrollRecords as any,
    supabaseTable: 'synced_payroll',
    rpcName: 'upsert_synced_payroll',
    toCloudRecord: (item: Partial<PayrollRecord> & { id?: number }) => ({
      p_local_id: item.id,
      p_employee_id: item.employeeId ?? 0,
      p_period: item.period || '',
      p_base_salary: item.baseSalary ?? 0,
      p_bonuses: item.bonuses ?? 0,
      p_deductions: item.deductions ?? 0,
      p_absence_deductions: item.absenceDeductions ?? 0,
      p_net_salary: item.netSalary ?? 0,
      p_status: item.status || 'pending',
      p_paid_at: item.paidAt || null,
      p_notes: item.notes || '',
    }),
    fromCloudRecord: (r: any): PayrollRecord => ({
      id: r.local_id,
      employeeId: r.employee_id ?? 0,
      period: r.period || '',
      baseSalary: Number(r.base_salary) || 0,
      bonuses: Number(r.bonuses) || 0,
      deductions: Number(r.deductions) || 0,
      absenceDeductions: Number(r.absence_deductions) || 0,
      netSalary: Number(r.net_salary) || 0,
      status: r.status || 'pending',
      paidAt: r.paid_at || undefined,
      notes: r.notes || '',
      createdAt: new Date(r.created_at || Date.now()),
      updatedAt: new Date(r.updated_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  subscriptionPlans: {
    dexieTable: db.subscriptionPlans as any,
    supabaseTable: 'synced_subscription_plans',
    rpcName: 'upsert_synced_subscription_plan',
    toCloudRecord: (item: Partial<SubscriptionPlan> & { id?: number }) => ({
      p_local_id: item.id,
      p_name: item.name || '',
      p_type: item.type || 'subscription',
      p_duration: item.duration || '',
      p_sessions_count: item.sessionsCount ?? 0,
      p_price: item.price ?? 0,
      p_description: item.description || '',
      p_program_id: item.programId ?? 0,
      p_is_active: item.isActive ?? true,
    }),
    fromCloudRecord: (r: any): SubscriptionPlan => ({
      id: r.local_id,
      name: r.name || '',
      type: r.type || 'subscription',
      duration: r.duration || '',
      sessionsCount: r.sessions_count || 0,
      price: Number(r.price) || 0,
      description: r.description || '',
      programId: r.program_id || 0,
      isActive: r.is_active ?? true,
      createdAt: new Date(r.created_at || Date.now()),
    }),
  },
};
