import { db } from '@/lib/db/dexie-db';
import type { Table } from 'dexie';
import type { Product, Program, SubscriptionPlan, Sale, Employee, Absence, PayrollRecord, Coach, Expense, PrivateSession, GymEvent, EventRegistration, Reward, ProductCategory, WhatsAppCampaign, Member, Payment, CheckIn, PointsLedger, PinUser } from '@/lib/db/dexie-db';

export interface SyncEntityConfig<T> {
  dexieTable: Table<T, number>;
  supabaseTable: string;
  rpcName: string;
  toCloudRecord: (item: Partial<T> & { id?: number }) => Record<string, unknown>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  fromCloudRecord: (record: any) => T;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const ENTITY_REGISTRY: Record<string, SyncEntityConfig<any>> = {
  products: {
    dexieTable: db.products,
    supabaseTable: 'synced_products',
    rpcName: 'upsert_synced_product',
    toCloudRecord: (item: Partial<Product> & { id?: number }) => ({
      p_local_id: item.id,
      p_barcode: item.barcode || '',
      p_name: item.name || '',
      p_buy_price: item.buyPrice ?? 0,
      p_sell_price: item.sellPrice ?? 0,
      p_stock: item.stock ?? 0,
      p_photo: item.photo || '',
    }),
    fromCloudRecord: (r): Product => ({
      id: r.local_id,
      barcode: r.barcode || '',
      name: r.name || '',
      buyPrice: Number(r.buy_price) || 0,
      sellPrice: Number(r.sell_price) || 0,
      stock: r.stock || 0,
      photo: r.photo || '',
      createdAt: new Date(r.created_at || Date.now()),
    }),
  },

  programs: {
    dexieTable: db.programs,
    supabaseTable: 'synced_programs',
    rpcName: 'upsert_synced_program',
    toCloudRecord: (item: Partial<Program> & { id?: number }) => ({
      p_local_id: item.id,
      p_name: item.name || '',
      p_description: item.description || '',
      p_price: item.price ?? 0,
      p_is_active: item.isActive ?? true,
    }),
    fromCloudRecord: (r): Program => ({
      id: r.local_id,
      name: r.name || '',
      description: r.description || '',
      price: Number(r.price) || 0,
      isActive: r.is_active ?? true,
      createdAt: new Date(r.created_at || Date.now()),
    }),
  },

  sales: {
    dexieTable: db.sales,
    supabaseTable: 'synced_sales',
    rpcName: 'upsert_synced_sale',
    toCloudRecord: (item: Partial<Sale> & { id?: number }) => ({
      p_local_id: item.id,
      p_items_json: JSON.stringify(item.items || []),
      p_total: item.total ?? 0,
      p_paid: item.paid ?? 0,
      p_change_amount: item.change ?? 0,
      p_payment_mode: item.paymentMode || 'cash',
    }),
    fromCloudRecord: (r): Sale => ({
      id: r.local_id,
      items: JSON.parse(r.items_json || '[]'),
      total: Number(r.total) || 0,
      paid: Number(r.paid) || 0,
      change: Number(r.change_amount) || 0,
      paymentMode: r.payment_mode || 'cash',
      createdAt: new Date(r.created_at || Date.now()),
      updatedAt: new Date(r.updated_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  employees: {
    dexieTable: db.employees,
    supabaseTable: 'synced_employees',
    rpcName: 'upsert_synced_employee',
    toCloudRecord: (item: Partial<Employee> & { id?: number }) => ({
      p_local_id: item.id,
      p_gym_user_id: item.gymUserId || null,
      p_coach_id: item.coachId || null,
      p_name: item.name || '',
      p_phone: item.phone || '',
      p_email: item.email || '',
      p_address: item.address || '',
      p_position: item.position || '',
      p_department: item.department || '',
      p_hire_date: item.hireDate || '',
      p_contract_type: item.contractType || 'cdi',
      p_base_salary: item.baseSalary ?? 0,
      p_bank_name: item.bankName || '',
      p_bank_rib: item.bankRib || '',
      p_emergency_contact: item.emergencyContact || '',
      p_emergency_phone: item.emergencyPhone || '',
      p_social_security: item.socialSecurityNumber || '',
      p_birth_date: item.birthDate || '',
      p_gender: item.gender || 'other',
      p_photo: item.photo || '',
      p_is_active: item.isActive ?? true,
    }),
    fromCloudRecord: (r): Employee => ({
      id: r.local_id,
      gymUserId: r.gym_user_id || undefined,
      coachId: r.coach_id || undefined,
      name: r.name || '',
      phone: r.phone || '',
      email: r.email || '',
      address: r.address || '',
      position: r.position || '',
      department: r.department || '',
      hireDate: r.hire_date || '',
      contractType: r.contract_type || 'cdi',
      baseSalary: Number(r.base_salary) || 0,
      bankName: r.bank_name || '',
      bankRib: r.bank_rib || '',
      emergencyContact: r.emergency_contact || '',
      emergencyPhone: r.emergency_phone || '',
      socialSecurityNumber: r.social_security || '',
      birthDate: r.birth_date || '',
      gender: r.gender || 'other',
      photo: r.photo || '',
      isActive: r.is_active ?? true,
      createdAt: new Date(r.created_at || Date.now()),
      updatedAt: new Date(r.updated_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  absences: {
    dexieTable: db.absences ,
    supabaseTable: 'synced_absences',
    rpcName: 'upsert_synced_absence',
    toCloudRecord: (item: Partial<Absence> & { id?: number }) => ({
      p_local_id: item.id,
      p_employee_id: item.employeeId ?? 0,
      p_type: item.type || 'other',
      p_start_date: item.startDate || '',
      p_end_date: item.endDate || '',
      p_reason: item.reason || '',
      p_status: item.status || 'pending',
      p_approved_by: item.approvedBy || null,
    }),
    fromCloudRecord: (r): Absence => ({
      id: r.local_id,
      employeeId: r.employee_id ?? 0,
      type: r.type || 'other',
      startDate: r.start_date || '',
      endDate: r.end_date || '',
      reason: r.reason || '',
      status: r.status || 'pending',
      approvedBy: r.approved_by || undefined,
      createdAt: new Date(r.created_at || Date.now()),
      updatedAt: new Date(r.updated_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  payrollRecords: {
    dexieTable: db.payrollRecords ,
    supabaseTable: 'synced_payroll',
    rpcName: 'upsert_synced_payroll',
    toCloudRecord: (item: Partial<PayrollRecord> & { id?: number }) => ({
      p_local_id: item.id,
      p_employee_id: item.employeeId ?? 0,
      p_period: item.period || '',
      p_base_salary: item.baseSalary ?? 0,
      p_bonuses: item.bonuses ?? 0,
      p_deductions: item.deductions ?? 0,
      p_absence_deductions: item.absenceDeductions ?? 0,
      p_net_salary: item.netSalary ?? 0,
      p_status: item.status || 'pending',
      p_paid_at: item.paidAt || null,
      p_notes: item.notes || '',
    }),
    fromCloudRecord: (r): PayrollRecord => ({
      id: r.local_id,
      employeeId: r.employee_id ?? 0,
      period: r.period || '',
      baseSalary: Number(r.base_salary) || 0,
      bonuses: Number(r.bonuses) || 0,
      deductions: Number(r.deductions) || 0,
      absenceDeductions: Number(r.absence_deductions) || 0,
      netSalary: Number(r.net_salary) || 0,
      status: r.status || 'pending',
      paidAt: r.paid_at || undefined,
      notes: r.notes || '',
      createdAt: new Date(r.created_at || Date.now()),
      updatedAt: new Date(r.updated_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  subscriptionPlans: {
    dexieTable: db.subscriptionPlans ,
    supabaseTable: 'synced_subscription_plans',
    rpcName: 'upsert_synced_subscription_plan',
    toCloudRecord: (item: Partial<SubscriptionPlan> & { id?: number }) => ({
      p_local_id: item.id,
      p_name: item.name || '',
      p_type: item.type || 'subscription',
      p_duration: item.duration || '',
      p_sessions_count: item.sessionsCount ?? 0,
      p_price: item.price ?? 0,
      p_description: item.description || '',
      p_program_id: item.programId ?? 0,
      p_is_active: item.isActive ?? true,
    }),
    fromCloudRecord: (r): SubscriptionPlan => ({
      id: r.local_id,
      name: r.name || '',
      type: r.type || 'subscription',
      duration: r.duration || '',
      sessionsCount: r.sessions_count || 0,
      price: Number(r.price) || 0,
      description: r.description || '',
      programId: r.program_id || 0,
      isActive: r.is_active ?? true,
      createdAt: new Date(r.created_at || Date.now()),
    }),
  },

  coaches: {
    dexieTable: db.coaches ,
    supabaseTable: 'synced_coaches',
    rpcName: 'upsert_synced_coach',
    toCloudRecord: (item: Partial<Coach> & { id?: number }) => ({
      p_local_id: item.id,
      p_name: item.name || '',
      p_phone: item.phone || '',
      p_availability: JSON.stringify(item.availability || []),
      p_program_ids: JSON.stringify(item.programIds || []),
      p_is_active: item.isActive ?? true,
    }),
    fromCloudRecord: (r): Coach => ({
      id: r.local_id,
      name: r.name || '',
      phone: r.phone || '',
      availability: typeof r.availability === 'string' ? JSON.parse(r.availability) : (r.availability || []),
      programIds: typeof r.program_ids === 'string' ? JSON.parse(r.program_ids) : (r.program_ids || []),
      isActive: r.is_active ?? true,
      createdAt: new Date(r.created_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  expenses: {
    dexieTable: db.expenses ,
    supabaseTable: 'synced_expenses',
    rpcName: 'upsert_synced_expense',
    toCloudRecord: (item: Partial<Expense> & { id?: number }) => ({
      p_local_id: item.id,
      p_category: item.category || '',
      p_amount: item.amount ?? 0,
      p_date: item.date ? new Date(item.date).toISOString() : new Date().toISOString(),
      p_description: item.description || '',
    }),
    fromCloudRecord: (r): Expense => ({
      id: r.local_id,
      category: r.category || '',
      amount: Number(r.amount) || 0,
      date: new Date(r.date || r.created_at || Date.now()),
      description: r.description || '',
      createdAt: new Date(r.created_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  privateSessions: {
    dexieTable: db.privateSessions ,
    supabaseTable: 'synced_private_sessions',
    rpcName: 'upsert_synced_private_session',
    toCloudRecord: (item: Partial<PrivateSession> & { id?: number }) => ({
      p_local_id: item.id,
      p_member_id: item.memberId ?? 0,
      p_member_name: item.memberName || '',
      p_coach_id: item.coachId ?? 0,
      p_coach_name: item.coachName || '',
      p_date: item.date || '',
      p_time: item.time || '',
      p_duration: item.duration ?? 60,
      p_price: item.price ?? 0,
      p_status: item.status || 'pending',
    }),
    fromCloudRecord: (r): PrivateSession => ({
      id: r.local_id,
      memberId: r.member_id ?? 0,
      memberName: r.member_name || '',
      coachId: r.coach_id ?? 0,
      coachName: r.coach_name || '',
      date: r.date || '',
      time: r.time || '',
      duration: r.duration || 60,
      price: Number(r.price) || 0,
      status: r.status || 'pending',
      createdAt: new Date(r.created_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  events: {
    dexieTable: db.events ,
    supabaseTable: 'synced_events',
    rpcName: 'upsert_synced_event',
    toCloudRecord: (item: Partial<GymEvent> & { id?: number }) => ({
      p_local_id: item.id,
      p_name: item.name || '',
      p_type: item.type || 'event',
      p_date: item.date || '',
      p_price: item.price ?? 0,
      p_location: item.location || '',
      p_max_participants: item.maxParticipants ?? 30,
      p_participants: item.participants ?? 0,
      p_status: item.status || 'open',
      p_description: item.description || '',
    }),
    fromCloudRecord: (r): GymEvent => ({
      id: r.local_id,
      name: r.name || '',
      type: r.type || 'event',
      date: r.date || '',
      price: Number(r.price) || 0,
      location: r.location || '',
      maxParticipants: r.max_participants || 30,
      participants: r.participants || 0,
      status: r.status || 'open',
      description: r.description || '',
      createdAt: new Date(r.created_at || Date.now()),
      updatedAt: new Date(r.updated_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  eventRegistrations: {
    dexieTable: db.eventRegistrations ,
    supabaseTable: 'synced_event_registrations',
    rpcName: 'upsert_synced_event_registration',
    toCloudRecord: (item: Partial<EventRegistration> & { id?: number }) => ({
      p_local_id: item.id,
      p_event_id: item.eventId ?? 0,
      p_event_name: item.eventName || '',
      p_member_id: item.memberId ?? 0,
      p_member_name: item.memberName || '',
      p_amount_paid: item.amountPaid ?? 0,
      p_status: item.status || 'registered',
      p_registered_at: item.registeredAt ? item.registeredAt.toISOString() : new Date().toISOString(),
      p_checked_in_at: item.checkedInAt ? item.checkedInAt.toISOString() : null,
    }),
    fromCloudRecord: (r): EventRegistration => ({
      id: r.local_id,
      eventId: r.event_id ?? 0,
      eventName: r.event_name || '',
      memberId: r.member_id ?? 0,
      memberName: r.member_name || '',
      amountPaid: Number(r.amount_paid) || 0,
      status: r.status || 'registered',
      registeredAt: new Date(r.registered_at || r.created_at || Date.now()),
      checkedInAt: r.checked_in_at ? new Date(r.checked_in_at) : undefined,
      createdAt: new Date(r.created_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  rewards: {
    dexieTable: db.rewards ,
    supabaseTable: 'synced_rewards',
    rpcName: 'upsert_synced_reward',
    toCloudRecord: (item: Partial<Reward> & { id?: number }) => ({
      p_local_id: item.id,
      p_name: item.name || '',
      p_description: item.description || '',
      p_points_required: item.pointsRequired ?? 0,
      p_stock: item.stock ?? 0,
      p_image: item.image || '',
    }),
    fromCloudRecord: (r): Reward => ({
      id: r.local_id,
      name: r.name || '',
      description: r.description || '',
      pointsRequired: r.points_required || 0,
      stock: r.stock || 0,
      image: r.image || '',
      createdAt: new Date(r.created_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  productCategories: {
    dexieTable: db.productCategories ,
    supabaseTable: 'synced_product_categories',
    rpcName: 'upsert_synced_product_category',
    toCloudRecord: (item: Partial<ProductCategory> & { id?: number }) => ({
      p_local_id: item.id,
      p_name: item.name || '',
    }),
    fromCloudRecord: (r): ProductCategory => ({
      id: r.local_id,
      name: r.name || '',
      createdAt: new Date(r.created_at || Date.now()),
    }),
  },

  whatsappCampaigns: {
    dexieTable: db.whatsappCampaigns ,
    supabaseTable: 'synced_whatsapp_campaigns',
    rpcName: 'upsert_synced_whatsapp_campaign',
    toCloudRecord: (item: Partial<WhatsAppCampaign> & { id?: number }) => ({
      p_local_id: item.id,
      p_template: item.template || '',
      p_member_id: item.memberId ?? 0,
      p_member_name: item.memberName || '',
      p_phone: item.phone || '',
      p_message: item.message || '',
      p_status: item.status || 'sent',
    }),
    fromCloudRecord: (r): WhatsAppCampaign => ({
      id: r.local_id,
      template: r.template || '',
      memberId: r.member_id ?? 0,
      memberName: r.member_name || '',
      phone: r.phone || '',
      message: r.message || '',
      status: r.status || 'sent',
      createdAt: new Date(r.created_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  members: {
    dexieTable: db.members,
    supabaseTable: 'synced_members',
    rpcName: 'upsert_synced_member',
    toCloudRecord: (item: Partial<Member> & { id?: number }) => ({
      p_local_id: item.id,
      p_phone: item.phone || '',
      p_first_name: item.firstName || '',
      p_last_name: item.lastName || '',
      p_birth_date: item.birthDate || '',
      p_address: item.address || '',
      p_gender: item.gender || 'other',
      p_blood_type: item.bloodType || '',
      p_photo: item.photo || '',
      p_coach_id: item.coachId ?? null,
      p_program_id: item.programId ?? null,
      p_sessions_left: item.sessionsLeft ?? 0,
      p_program_amount: item.programAmount ?? 0,
      p_amount_paid: item.amountPaid ?? 0,
      p_balance_due: item.balanceDue ?? 0,
      p_discount: item.discount ?? 0,
      p_advance: item.advance ?? 0,
      p_subscription_type: item.subscriptionType || 'free_session',
      p_subscription_duration: item.subscriptionDuration || '',
      p_status: item.status || 'active',
      p_fidelity_points: item.fidelityPoints ?? 0,
      p_rfid_code: item.rfidCode || '',
      p_is_blocked: item.isBlocked ?? false,
      p_block_reason: item.blockReason || null,
      p_block_date: item.blockDate ? item.blockDate.toISOString() : null,
      p_blocked_until: item.blockedUntil ? item.blockedUntil.toISOString() : null,
      p_email: item.email || null,
      p_emergency_contact_name: item.emergencyContactName || null,
      p_emergency_contact_phone: item.emergencyContactPhone || null,
      p_allergies: item.allergies || null,
      p_weight: item.weight ?? null,
      p_weight_current: item.weightCurrent ?? null,
      p_height: item.height ?? null,
      p_fitness_goal: item.fitnessGoal || null,
      p_experience_level: item.experienceLevel || null,
      p_referred_by: item.referredBy ?? 0,
    }),
    fromCloudRecord: (r): Member => ({
      id: r.local_id,
      phone: r.phone || '',
      firstName: r.first_name || '',
      lastName: r.last_name || '',
      birthDate: r.birth_date || '',
      address: r.address || '',
      gender: r.gender || 'other',
      bloodType: r.blood_type || '',
      photo: r.photo || '',
      coachId: r.coach_id ?? undefined,
      programId: r.program_id ?? undefined,
      sessionsLeft: r.sessions_left || 0,
      programAmount: r.program_amount || 0,
      amountPaid: r.amount_paid || 0,
      balanceDue: r.balance_due || 0,
      discount: r.discount || 0,
      advance: r.advance || 0,
      subscriptionType: r.subscription_type || 'free_session',
      subscriptionDuration: r.subscription_duration || '',
      status: r.status || 'active',
      fidelityPoints: r.fidelity_points || 0,
      rfidCode: r.rfid_code || '',
      isBlocked: r.is_blocked ?? false,
      blockReason: r.block_reason || null,
      blockDate: r.block_date ? new Date(r.block_date) : undefined,
      blockedUntil: r.blocked_until ? new Date(r.blocked_until) : undefined,
      email: r.email || undefined,
      emergencyContactName: r.emergency_contact_name || undefined,
      emergencyContactPhone: r.emergency_contact_phone || undefined,
      allergies: r.allergies || undefined,
      weight: r.weight ?? undefined,
      weightCurrent: r.weight_current ?? undefined,
      height: r.height ?? undefined,
      fitnessGoal: r.fitness_goal || undefined,
      experienceLevel: r.experience_level || undefined,
      referredBy: r.referred_by || undefined,
      createdAt: new Date(r.created_at || Date.now()),
      updatedAt: new Date(r.updated_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  payments: {
    dexieTable: db.payments,
    supabaseTable: 'synced_payments',
    rpcName: '',
    toCloudRecord: (item: Partial<Payment> & { id?: number }) => ({
      local_id: item.id,
      member_id: item.memberId,
      amount: item.amount,
      type: item.type,
      mode: item.mode,
      date: item.date ? new Date(item.date).toISOString() : new Date().toISOString(),
      notes: item.description,
      created_at: item.createdAt ? new Date(item.createdAt).toISOString() : new Date().toISOString(),
    }),
    fromCloudRecord: (r): Payment => ({
      id: r.local_id,
      memberId: r.member_id,
      amount: Number(r.amount) || 0,
      type: r.type || 'subscription',
      mode: r.mode || 'cash',
      date: new Date(r.date || r.created_at || Date.now()),
      description: r.notes || '',
      createdAt: new Date(r.created_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  checkins: {
    dexieTable: db.checkins,
    supabaseTable: 'synced_checkins',
    rpcName: '',
    toCloudRecord: (item: Partial<CheckIn> & { id?: number }) => ({
      local_id: item.id,
      member_id: item.memberId,
      timestamp: item.timestamp ? new Date(item.timestamp).toISOString() : new Date().toISOString(),
      type: item.type,
    }),
    fromCloudRecord: (r): CheckIn => ({
      id: r.local_id,
      memberId: r.member_id,
      timestamp: new Date(r.timestamp || r.created_at || Date.now()),
      type: r.type || 'checkin',
      syncStatus: 'synced',
    }),
  },

  pointsLedger: {
    dexieTable: db.pointsLedger,
    supabaseTable: 'synced_points_ledger',
    rpcName: '',
    toCloudRecord: (item: Partial<PointsLedger> & { id?: number }) => ({
      local_id: item.id,
      member_id: item.memberId,
      points: item.points,
      type: item.type,
      reference_id: item.referenceId,
      created_at: item.createdAt ? new Date(item.createdAt).toISOString() : new Date().toISOString(),
    }),
    fromCloudRecord: (r): PointsLedger => ({
      id: r.local_id,
      memberId: r.member_id,
      memberName: r.member_name || '',
      points: Number(r.points) || 0,
      type: r.type || 'earn',
      reason: r.reason || '',
      referenceId: r.reference_id || undefined,
      referenceType: r.reference_type || undefined,
      balanceAfter: Number(r.balance_after) || 0,
      createdAt: new Date(r.created_at || Date.now()),
      syncStatus: 'synced',
    }),
  },

  pinUsers: {
    dexieTable: db.pinUsers,
    supabaseTable: 'synced_pin_users',
    rpcName: '',
    toCloudRecord: (item: Partial<PinUser> & { id?: number }) => ({
      local_id: item.id,
      username: item.username || '',
      password: item.password || '',
      role: item.role,
      name: item.name || '',
      phone: item.phone || null,
      is_locked: item.isLocked || false,
      pin: item.pin || '',
      created_at: item.createdAt ? new Date(item.createdAt).toISOString() : new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }),
    fromCloudRecord: (r): PinUser => ({
      id: r.local_id,
      username: r.username || '',
      password: r.password || '',
      pin: r.pin || '',
      role: r.role || 'reception',
      name: r.name || '',
      phone: r.phone || undefined,
      isLocked: r.is_locked || false,
      createdAt: new Date(r.created_at || Date.now()),
      syncStatus: 'synced',
    }),
  },
};
